/*
 * MainPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ntek;

import java.util.logging.Handler;
import java.util.logging.LogRecord;

import javax.swing.JFrame;

import com.ntek.logcat.LogCatFrame;
import com.ntek.logcat.Logcat;

/**
 * 
 * @author Nitro
 */
public class MainPanel extends javax.swing.JPanel {

	private boolean flagLogcat = false;
	private LogCatFrame logCatFrame = null;
	private Thread logCatThread = null;

	/** Creates new form MainPanel */
	public MainPanel() {
		initComponents();
		logCatFrame = new LogCatFrame(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jButton1 = new javax.swing.JButton();

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);


		jButton1.setText("LogCat");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(87, 87, 87)
						.addComponent(jButton1)
						.addContainerGap(120, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(144, Short.MAX_VALUE)
						.addComponent(jButton1).addGap(66, 66, 66)));
	}// </editor-fold>
	//GEN-END:initComponents

	private Handler logCatHandler = new Handler() {

		@Override
		public void publish(LogRecord arg0) {
			// TODO Auto-generated method stub

		}

		@Override
		public void flush() {
			// TODO Auto-generated method stub

		}

		@Override
		public void close() throws SecurityException {
			// TODO Auto-generated method stub

		}
	};

	@SuppressWarnings("deprecation")
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		if (flagLogcat) {
			logCatFrame.setVisible(false);
			logCatThread.stop();
			flagLogcat = false;
		} else {
			logCatThread = new Thread(new Logcat(logCatHandler, logCatFrame));
			logCatThread.start();
			logCatFrame.setVisible(true);
			flagLogcat = true;
		}
	}

	public void setFlagLogcat(boolean arg) {
		flagLogcat = arg;
	}

	public Thread getLogCatThread() {
		return logCatThread;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	// End of variables declaration//GEN-END:variables

}